---
include:
  - board: seeeduino_xiao_ble
    shield: mona2_r
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: mona2_l
    # Peripheral 側は BLE 経由で Central と通信するため studio-rpc-usb-uart は不要
  - board: seeeduino_xiao_ble
    shield: settings_reset
